image: docker:latest
services:
  - docker:dind
 
stages: 
  - build
  - package
  - deploy
  
maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
     - target/*war
     
 docekr-build:
  stage: package
  before-script:
    -docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    -docker build --pull -t "CI_REGITRY_IMAGE" .
    -docker push "$CI_REGISTRY_IMAGE"
    
    
k8s-deploy:
  stage: deploy
  script:
    - docker run -d -p 8080:8080 -- name new_project "$CI_REGISTRY_IMAGE"
